### ISSUE TITLE
Merge or Link README md and mdx

### ISSUE THREAD

**Issue by stefan-wild** [madebywild/eslint-config#2]
## Why
Both do similar things and need manual syncing, 

## What
Maybe reference `README.md` inside `README.mdx`, that way we still have the frontmatter and extra info in the mdx, without having to duplicate stuff in both readme files

## Definition of done
A clear and concise description of what you expected to happen in order to consider the feature completed.

- Description/Installation/Usage only needs to be updated in one file, and show up both in https://docs.wild.plus/ and in the repo readme

**Comment by stefan-wild** [comment]
ok, I had a look, and I don't think its worth it

```
import Readme from './README.md';
<Readme />
```
should work, but all `README.md` files are ignored with the `doczrc.js` config

I got it to work with raw-loader and `markdown-to-jsx`, but then the styling is different, especially for code blocks (also with different classNames for the code highlighting)

```
import { compiler } from 'markdown-to-jsx';
import Readme from '!!raw-loader!../../submodules/eslint-config/README.md';

<section>{compiler(Readme, {})}</section>
```
[comparison of inlined readme, and current status](https://files.wild.as/5N66ME)

**Comment by lorenzomigliorero** [comment]
There isn't a convenient way to do that.
```jsx
import Readme from './README.md';
<Readme />
```
Technically, this should work, but we need to ignore the README.md file from _docz_.
As @stefan-wild suggest, we can simply link the docs.wild.plus page from the README.md.
